class:
    - {name: "\\ModulesGarden\\Servers\\HetznerVps\\Core\\Http\\Request", method: "build",                        args: []}
    - {name: '\\ModulesGarden\\Servers\\HetznerVps\\Core\\Http\\View\\Smarty',  method: "get",                    args: [NULL,NULL]}
    - {name: '\\ModulesGarden\\Servers\\HetznerVps\\Core\\HandlerError\\Logger',  method: "get",                  args: ["default","debug.log","warning.log","error.log"]}
    - {name: '\\ModulesGarden\\Servers\\HetznerVps\\Core\\RegisterManager\\Register',  method: "getInstace",      args: []}
    - {name: '\\ModulesGarden\\Servers\\HetznerVps\\Core\\Helper\\Lang',  method: "getInstance",                  args: [NULL,NULL]}
