- \ModulesGarden\Servers\HetznerVps\Core\Lang\Lang
- \ModulesGarden\Servers\HetznerVps\Core\App\Controllers\Instances\Addon\Config
- \ModulesGarden\Servers\HetznerVps\Core\UI\Widget\Sidebar\SidebarService
- \ModulesGarden\Servers\HetznerVps\Core\Helper\WhmcsParams
- \ModulesGarden\Servers\HetznerVps\Core\App\AppParamsContainer