<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '3.9.0';
$moduleRevision = '1874e3086fe3eadea0334a95cc831240ec0f5863';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Advanced_Billing_For_WHMCS';