services:
  lic_server:
    build: .
    container_name: lic_server
    volumes:
      - ./whmcs:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/php.ini
      - ./config/cron:/etc/cron.d/whmcs-cron  # Mount cron file
    ports:
      - "7081:80"
    env_file:
      - .env  # Load .env file for environment variables
    networks:
      - lic_server-network2
    depends_on:
      - lic_server_db

  lic_server_db:
    image: mysql:8.0
    container_name: lic_server_db
    env_file:
      - .env  # Load .env file for MySQL environment variables
    networks:
      - lic_server-network2

  lic_server_pma:
    image: phpmyadmin/phpmyadmin
    container_name: lic_server_pma
    env_file:
      - .env  # Load .env file for phpMyAdmin environment variables
    ports:
      - "7079:80"
    depends_on:
      - lic_server_db
    networks:
      - lic_server-network2

volumes:
  db_data:

networks:
  lic_server-network2:
    driver: bridge
