version: '1.5.0'
systemName: 'HetznerVps'
name: 'Hetzner Cloud Servers'
description: 'Hetzner Cloud Servers For WHMCS.<br>For more info visit our <a href="http://www.docs.modulesgarden.com/CHANGE_ME" style="color: #4169E1;" target="_blank">Wiki</a>.'
clientareaName: 'MG Demo'
author: '<a href="http://www.modulesgarden.com" targer="_blank">ModulesGarden</a>'
moduleIcon: 'ip_manager'
