<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.10.2';
$moduleRevision = '8c8b7586b7ee2f26f565e20f0f7bd87edfc508c7';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Hetzner_VPS_For_WHMCS';