<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.10.0';
$moduleRevision = '630b0c6768a78ae22a082e8453d65785fb1acd11';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Hetzner_VPS_For_WHMCS';