<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '2.3.0-b1-final';
$moduleRevision = '29cc2ee21d0a7883b1243b0c5fe1eb68483c3b6a';
$moduleWikiUrl = 'https://www.rstudio.net';