<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.2.4';
$moduleRevision = 'd96a70d962f89b519d2d527d0f890d01b25bea30';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Lagom_One_Step_Order_Form_For_WHMCS';