<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '1.2.5';
$moduleRevision = '78c5bada3b1f5d94a035f939e7005764af1a4df6';
$moduleWikiUrl = 'https://www.docs.modulesgarden.com/Lagom_One_Step_Order_Form_For_WHMCS';