<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '2.10.3';
$moduleRevision = 'bfd36df27233da68c246f2365f1e1685b98a57f5';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/CRM_For_WHMCS';