<?php
/*
 * File generated by ModulesGarden packages system
 * 
 * Below you can find current version & revision of this module
 */

$moduleVersion = '2.10.2';
$moduleRevision = 'b51062935e3891c2f6dafcd6341cdb29b673726b';
$moduleWikiUrl = 'http://www.docs.modulesgarden.com/CRM_For_WHMCS';